apiVersion: v1
kind: ServiceList
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: producer
    spec:
      ports:
        - port: 3000
          targetPort: 3000
      selector:
        app: producer
  - apiVersion: v1
    kind: Service
    metadata:
      name: nginx
    spec:
      sessionAffinity: ClientIP
      type: LoadBalancer
      ports:
        - port: 80
          targetPort: 8080
      selector:
        app: nginx
  - apiVersion: v1
    kind: Service
    metadata:
      name: rabbitmq
    spec:
      ports:
        - port: 5672
          targetPort: 5672
      selector:
        app: rabbitmq
---
apiVersion: extensions/v1beta1
kind: DeploymentList
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        app: producer
      name: producer
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: producer
        spec:
          containers:
            - image: gcr.io/core-falcon-135017/producer:latest
              name: producer
              ports:
              - containerPort: 3000
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: consumer
      labels:
        app: consumer
    spec:
      replicas: 4
      template:
        metadata:
          labels:
            app: consumer
        spec:
          containers:
            - name: consumer
              image: gcr.io/core-falcon-135017/consumer:latest
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: gcr.io/core-falcon-135017/nginx:latest
              ports:
                - containerPort: 8080
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: rabbitmq
        spec:
          containers:
            - name: rabbitmq
              image: "rabbitmq"
